[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes configuration
[functions]
  node_bundler = "esbuild"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes should not be cached
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_BASE = "https://newems.netlify.app"

# Environment variables for preview
[context.deploy-preview.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_BASE = "https://deploy-preview-{BRANCH}--newems.netlify.app"

# Environment variables for branch deploys
[context.branch-deploy.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_BASE = "https://{BRANCH}--newems.netlify.app"